data:
    name: 'hpatches' #hpatches
    data_dir: './data/hpatches' #./data/hpatches
    export_dir: './data/repeatibility/hpatches/magic_cocov2'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
        resize: [240,320]
    homography_adaptation:
        num: 0
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
model:
    name: 'magicpoint' #superpoint
    bb_name: "EfficientBBV2"       # "VGGBackboneBN", "VGGBackbone", "EfficientBB"
    pretrained_model: './export_coco_v2/mg_coco_0023_0.594.pth'
    grid_size: 8
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    learning_rate: 0.001
    nms: 4
    topk: 1000
    det_thresh: 0.001 # 0.001
    #batch_size: 50
    #eval_batch_size: 50

