data:
    name: 'hpatches' #hpatches
    data_dir: '/data/zebin/data/hpatches-sequences/hpatches-sequences-release' #./data/hpatches
    export_dir: '/data/zebin/train_cache/lfnet/repeatibility/export_efficientv2s_3'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
        resize: [240,320]
    homography_adaptation:
        num: 0
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
model:
    name: 'magicpoint' #superpoint
    bb_name: ""       # "VGGBackboneBN", "VGGBackbone", "EfficientBB"
    pretrained_model: '/data/zebin/lfnet/SuperPoint-Pytorch/export_efficientv2s_3/mg_syn_0198_0.076.pth'
    grid_size: 8
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    learning_rate: 0.001
    nms: 4
    topk: 1000
    det_thresh: 0.001 # 0.001
    #batch_size: 50
    #eval_batch_size: 50

