data:
    name: 'coco'
    resize: [240,320]
    src_image_path: '/data/zebin/data/coco/test2017'
    dst_label_path: '/data/zebin/data/mg_coco_v2s_1/labels/test2017/'
    dst_image_path: '/data/zebin/data/mg_coco_v2s_1/images/test2017/'
    dst_color_path: '/data/zebin/data/mg_coco_v2s_1/images/test2017_color/'
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        valid_border_margin: 3
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.85
            max_angle: 1.57
model:
    name: 'magicpoint'
    bb_name: "EfficientBBV2"       # "VGGBackboneBN", "VGGBackbone", "EfficientBB"
    grid_size: 8
    det_thresh: 0.015 #0.015
    nms: 4
    topk: 0
    pretrained_model: '/data/zebin/lfnet/SuperPoint-Pytorch/export_efficientv2s_3/mg_syn_0198_0.076.pth'
    det_head: #detector head
        feat_in_dim: 128