data:
    name: 'coco'
    resize: [240,320]
    src_image_path: './data/coco/test2017/'
    dst_label_path: './data/mg_coco_coco_3e-2/labels/test2017/'
    dst_image_path: './data/mg_coco_coco_3e-2/images/test2017/'
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        valid_border_margin: 3
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.85
            max_angle: 1.57
model:
    name: 'magicpoint'
    bb_name: "EfficientBBV2"       # "VGGBackboneBN", "VGGBackbone", "EfficientBB"
    grid_size: 8
    det_thresh: 0.015 #0.015
    nms: 4
    topk: 0
    pretrained_model: './export_efficientv2/mg_syn_0035_0.112.pth'
    det_head: #detector head
        feat_in_dim: 128